version: '3'
services:
    sparkmaster:       
        image: holtri/spark-master
        networks:
            - energydata_nw
        ports:
            - "8080:8080"
    node1:       
        image: holtri/cassandra-sparkslave
        depends_on:
            - sparkmaster 
        networks:
            - energydata_nw
        volumes:
            - ./node-1-data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=mega
            - SPARKMASTER=sparkmaster
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    node2:       
        image: holtri/cassandra-sparkslave
        depends_on:
            - sparkmaster
        networks:
            - energydata_nw
        volumes:
            - ./node-2-data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=mega
            - CASSANDRA_SEEDS=node1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000                        
networks:
    energydata_nw: