version: '3'
services:
# spark master
    sparkmaster:       
        image: holtri/spark-master
        ports:
            - "8080:8080"
        networks:
            - energydata_nw
            
# cassandra + spark-slave
    node1:       
        image: holtri/cassandra-sparkslave
        depends_on:
            - sparkmaster 
        volumes:
            - ./node-1-data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=mega
            - SPARKMASTER=sparkmaster
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        networks:
            - energydata_nw
 
    node2:       
        image: holtri/cassandra-sparkslave
        depends_on:
            - sparkmaster
        volumes:
            - ./node-2-data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=mega
            - CASSANDRA_SEEDS=node1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000   
        networks:
            - energydata_nw
# kafka
    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        networks:
            - energydata_nw
            
    broker:
        image: holtri/kafka-broker-connect
        hostname: broker
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        networks:
            - energydata_nw
            
    schema_registry:
        image: confluentinc/cp-schema-registry
        hostname: schema_registry
        depends_on:
          - zookeeper
          - broker
        ports:
          - "8081:8081"
        environment:
          SCHEMA_REGISTRY_HOST_NAME: schema_registry
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
        networks:
            - energydata_nw
            
# Jupyter Notebook
    jupyter:
        image: jupyter/pyspark-notebook
        # for custom password append  --NotebookApp.password='sha1:74ba40f8a388:c913541b7ee99d15d5ed31d4226bf7838f83a50e' (see https://hub.docker.com/r/jupyter/pyspark-notebook/)
        command: start-notebook.sh --NotebookApp.password='sha1:22050c912871:90073c0c3a0cb0ed20cbeb8c70a46dd52ed39d4c'
        volumes:
            - ./jupyter-data:/home/jovyan/work
        ports: 
            - "8888:8888"
            - "5040:4040"
        networks:
            - energydata_nw
            
networks:
    energydata_nw:
